### ISSUE TITLE
Which post hoc test should be used after Kruskal-Wallis test?

### ISSUE THREAD

**Issue by krajcsi** [cogstat/cogstat#102]
See a few options here https://scikit-posthocs.readthedocs.io/en/latest/intro.html#features or https://www.researchgate.net/post/Which_post_hoc_test_is_best_to_use_after_Kruskal_Wallis_test

**Comment by Majalebenicnik** [comment]
Dunn’s test is the most used nonparametric procedure (Midway et.al, 2020) and is considered as the appropriate post-hoc test following Kruskal-Wallis (Dinno, 2015). Current literature doesn’t offer any alternative nonparametric post-hoc test that would distinctly outperform Dunn’s.

Dinno, A. (2015). Nonparametric pairwise multiple comparisons in independent groups using Dunn's test. The Stata Journal, 15(1), 292-300.

Midway, S., Robertson, M., Flinn, S., & Kaller, M. (2020). Comparing multiple comparisons: practical guidance for choosing the best multiple comparisons test. PeerJ, 8, e10387. https://doi.org/10.7717/peerj.10387

**Comment by krajcsi** [comment]
Thanks, Maja! Based on that, we keep on using the Dunn's test.
