### ISSUE TITLE
Can't import excel file.   Oops, something went wrong, CogStat could not open the data. You may want to report the issue. Read more about how to report an issue here.  Error code: 'float' object is not iterable

### ISSUE THREAD

**Issue by fatema-alahmed** [cogstat/cogstat#161]
![image](https://user-images.githubusercontent.com/68123362/119979269-c2a82d80-bfcb-11eb-87dd-ba8c07c02aa9.png)

**Comment by krajcsi** [comment]
Hi, thanks for the report. What was the problem, or maybe the misunderstanding? Based on that we may help other users to avoid the issue by modifying the documentation, UI, etc.
