### ISSUE TITLE
appdirs in dependencies and not shipped with the package

### ISSUE THREAD

**Issue by lindemann09** [cogstat/cogstat#187]
Why is appdirs.py shipped with the package? It could be removed, if adding appdirs to the install_requires in the setup.py.

https://github.com/cogstat/cogstat/blob/b631025155459fa1bda77eb25dacb37052127e2e/setup.py#L12

https://github.com/cogstat/cogstat/blob/e592d34b7b005014a0ad30a8a0f479f6b06f75f0/cogstat/cogstat_config.py#L9

**Comment by krajcsi** [comment]
Fair enough. It was some older temporary solution that hasn't been sorted out. I'll fix it. Thanks for reporting!
