### ISSUE TITLE
Suggestion: use Levene-test or MC test according to the sample size

### ISSUE THREAD

**Issue by KDKokeny** [cogstat/cogstat#289]
According to the sources that I've read I suggest to use different tests depending on the sample size. If the sample contains less than 20 items, I advise to use non-parametic Levene-test, which is less sensitive to skewness compare to the original Levene's test (Nordstokke és Zumbo, 2007). Otherwise use Multiple Comparison test (Banga és Fox, 2013A; 2013B; Tests for Standard Deviations (Two or More Samples), n.d.). Both non-parametic Levene's test and MC test are more or less similar in type I or II errors (Banga és Fox; 2013B; Nordstokke és Zumbo, 2007).

Banga, S.J. and Fox, G.D. (2013A). On Bonett’s Robust Confidence Interval for a Ratio of Standard Deviations. White paper, Minitab Inc. 
Banga, S.J. and Fox, G.D. (2013B) A graphical multiple comparison procedure for several standard deviations. White paper, Minitab Inc.
Nordstokke, D. W., & Zumbo, B. D. (2007). A Cautionary Tale about Levene's Tests for Equal Variances. Journal of Educational Research & Policy Studies, 7(1), 1-14.

**Comment by krajcsi** [comment]
The comment is now moved to the relevant thread #86
