### ISSUE TITLE
Drag and drop or paste data

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#34]
Drag and drop or paste data ["Ctrl+V" or CogStat menu: "Data/Paste data"] doesn’t work.

Error Message: 
"Open data. Oops, something went wrong, CogStat could not run the analysis. You may want to report it."

The only way to open data is via "Ctrl+O" or CogStat menu: "Data/Open data file".

<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by krajcsi** [comment]
1. There was a yet unpublished fix for drag and drop issue: https://github.com/cogstat/cogstat/commit/8d6a26a9d5a0bbebe7566be0f0aefbd8e72eab87 This might fix the drag and drop problem. This will be available in the next release, or can be tried from the current master branch.

2. Paste works for me. Could you give me more information? What spreadsheet software? What are the exact steps? What is the CS version you mention (I don't understand the Latest update thing)?

**Comment by RRP89** [comment]
1. I checked my cogstat_gui.py data and as you can see in the following I have already updated it:

![cs_issue_2 0](https://cloud.githubusercontent.com/assets/22355317/26572633/fa2553f8-451a-11e7-88b8-2c731744f275.jpg)

Another problem must be responsible for this.

2. This happens: https://drive.google.com/open?id=0B7v148snAzyzQWlhNUQ2UXZsY00.
I used an ordinary text document (".txt"; e.g. [2_recognition.txt](https://github.com/cogstat/cogstat/files/1037572/2_recognition.txt)) regarding the right format for CS. I also tried it out with an excel spreadsheet (MSOffice2010).  Latest Update refers to  your e-mail from dec 14th in 2016,  in which you sent me the fixed context menu issue file: https://github.com/cogstat/cogstat/commit/8254ba39604b4c9eb81f44af7f2c07fc8844637c.

**Comment by krajcsi** [comment]
I checked this issue again. @RRP89 It is fantastic that your files are still available after so many years! :) Probably we had a Windows-specific drag-and-drop issue that we have fixed https://github.com/cogstat/cogstat/commit/9f3ad62659f0f3a581f79753e742a51b83e26420 Let me know if you still see this problem. Thanks again for reporting!
