### ISSUE TITLE
Column-/variable labels and result separation

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#35]
Column-/variable labels and results are “sandwiched”. A more clearly separation (e.g., by placeholder / tab stop) would be desirable. Especially with longer variables it’s difficult to recognize where a variable ends/starts. 

Examples (see yellow markings):

![bug2](https://cloud.githubusercontent.com/assets/22355317/22327805/52dbdee0-e3b9-11e6-85ea-81036f3d6bc7.jpg)

![bug3](https://cloud.githubusercontent.com/assets/22355317/22327807/5566e89e-e3b9-11e6-9567-92bce17f899f.jpg)

<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by RRP89** [comment]
By the way: Only the variables and their values aren't completely left-aligned (first example).

**Comment by krajcsi** [comment]
What do you mean by this? "Only the variables and their values aren't completely left-aligned (first example)."

**Comment by RRP89** [comment]
That's what I meant:

![cs_issue_4 0](https://cloud.githubusercontent.com/assets/22355317/26574100/6516b2ba-4520-11e7-8490-f93be4f2f388.jpg)

=> As you can see only the variables and their values aren't completely left-aligned. But it's really only a small thing.

**Comment by krajcsi** [comment]
In fact, it cannot be seen if the heading row is left aligned or not, because it fills the cells of that row. The visible difference is because the first example includes an empty leftmost cell.

Still, the separation issue should be solved.
