### ISSUE TITLE
25%, 50% and 75% percentiles

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#37]
25%, 50% and 75% percentiles are not offered in the descriptive statistics selection. An additional selection of them would be desirable, because they can help to understand the data more detailed (e.g. 25-/75% percentile ≙ 1. and 3. quartile [Q1; Q3]; 50% percentile ≙ Median). In addition they help someone who would like to calculate the interquartile range (Q3 - Q1). 

I'd recommend to add them as an optional/additional selection under descriptive statistics [CogStat menu: "Explore variables/Descriptives"] and I'd also recommend to add them automatically to a Q-Q-Plot (e.g. under or sideways to the plot).

<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by krajcsi** [comment]
1. I agree that (a) this would be useful to show an additional dispersion measure, and (b) it would display numerically the already displayed boxplot.

2. Why (and where exactly) the Q-Q plot is involved here?

**Comment by RRP89** [comment]
2.
a) At the time when I wrote this, I had read an [article](http://www.statistik-und-beratung.de/2012/09/parametrisch-oder-nichtparametrisch-das-ist-hier-die-frage/) (I'm not sure if it really was this article) in which it was postulated that Q-Q plot is better suited for the optical check of a normal distribution than a normal distribution curve:

[...] Wie erkenne ich, ob meine Daten normalverteilt sind? Am besten, man sieht sich einen Normalverteilungsplot an ... Liegen die Punkte schön auf einer Geraden, so sind die Daten normalverteilt. Es gibt auch Tests, die auf Normalverteilung untersuchen, z.B. Shapiro-Wilk, aber die sind oft zu streng. [...] 

translated:

[...] How do I know if my data is normal distributed? The best way is to take look at a normal distribution plot ... If the points are nicely on a straight line, the data is normally distributed. There are also tests that investigate normal distribution, e.g. Shapiro-Wilk, but they are often too strict. [...]

b) I thought it could be solved in a way similar to SPSS, that the descriptive data are simply added to the graph. For example, as in the graphic sideways (on the right) of the distribution curve:

![cs_issue_5 0](https://cloud.githubusercontent.com/assets/22355317/26575446/8e0f0f96-4525-11e7-9da1-072545b43acb.jpg)

**Comment by krajcsi** [comment]
Percentiles were added in 739be9c1392447329c7fba6cc0b8dec9defec06a and b21116b81e21acc0880dd545f544e7ba14b4d6ef
