### ISSUE TITLE
Skewness and kurtosis

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#38]
CogStat claims to be an "efficient statistical program", because it displays - compared to other statistical programs - more/(only) relevant data...

When running the test of normality (Shapiro-Wilk test), Skewness and Kurtosis will be display automatically. 
In my opinion, this isn't either necessary or relevant, because they only indicate that the more values are away from zero, the less likely the data aren’t normally distributed. But therefor (checking the normality) you already get the results of the Shapiro-Wilk test. In any case, the quantile-quantile-plot (Q-Q-Plot) is probably the most revealing for an optical check of the normality.

I'd recommend adding them only as an optional/additional selection under "Normality" [CogStat menu: "Explore variables/Normality"] for someone who is interested.

<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by krajcsi** [comment]
CS displays data graphically, offers descriptive numerical results, and test some properties with hypothesis tests. These are not interchangeable parts, all of them should be found in the output. See also https://github.com/cogstat/cogstat/wiki/How-to-compile-the-results%3F#results-to-compile Although Q-Q plot and hypothesis test for normality give partly overlapping and similar information as skewness and kurtosis, but descriptives should be offered, too. 

Therefore, I think skewneww and kurtosis should be kept.
