### ISSUE TITLE
Compare groups. Oops, something went wrong...

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#39]
Comparing groups with this data file "[2_recognition.txt](https://github.com/cogstat/cogstat/files/732230/2_recognition.txt)" doesn't work. 

Error message: 
“Compare groups. Oops, something went wrong, CogStat could not run the analysis. You may want to report it.”

Commands: 
Analysis/Compare groups [Ctrl+G] -> Group: <font color="green"><i>**condition**</i></font>; Dependent variable(s): <font color="green"><i>**relative_frequency**</i></font> -> OK

<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by krajcsi** [comment]
Confirmed. This must be fixed.
