### ISSUE TITLE
Repeated measures ANOVA with two within subject’s factors

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#40]
Repeated measures ANOVA with two within subject’s factors would be very desirable and would round off the program.

<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by krajcsi** [comment]
I absolutely agree. This is one of the main show stopper for many potential CS users. The main issue is that there is no multi-factor RM ANOVA implemented in Python. Here is the statsmodels issue for it: https://github.com/statsmodels/statsmodels/issues/749 Maybe the next statsmodels release might include it partly.

**Comment by hoechenberger** [comment]
statsmodels now supports RM-Anova: https://github.com/statsmodels/statsmodels/pull/3303

**Comment by jona-sassenhagen** [comment]
Yes, closed by #3303
