### ISSUE TITLE
Right aligned graphics disappear completely in saved output files

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#43]
If you get, for example, a left aligned normal distribution (graphic) and a quantile-quantile-plot (Q-Q-Plot) right aligned (sideways), then the Q-Q-Plot will disappear completely after saving the results (PDF).

<i>Used Software: Adobe Acrobat Reader DC 2015</i>
<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by RRP89** [comment]
This seems to be Adobe PDF Reader specific problem. But when using LibreOffice Draw right-aligned graphics and some texts are outside a page in Libre, which could be problematic when printing the results. If you want to check this, you'll find the result data right here: [result.pdf](https://github.com/cogstat/cogstat/files/1037453/result.pdf). 

![cs_issue_1 1](https://cloud.githubusercontent.com/assets/22355317/26571662/3367fd72-4517-11e7-96b8-fc4618188d7a.jpg)

![cs_issue_1 2](https://cloud.githubusercontent.com/assets/22355317/26571192/ec6cb1da-4514-11e7-9dbb-96d96412684e.jpg)

![cs_issue_1 3](https://cloud.githubusercontent.com/assets/22355317/26571199/f107d03a-4514-11e7-8daf-32585abf0d5c.jpg)

**Comment by krajcsi** [comment]
d534cd1e53b18ec08d94be6d1755c9ce56a15a6d and 5eedc1978edd9bb87311f38866f43b75380651d9 solved it.
