### ISSUE TITLE
Different fonts and font sizes after copying outputs

### ISSUE THREAD

**Issue by RRP89** [cogstat/cogstat#44]
If you keep the source formatting by copying the CogStat outputs, then the output gets (unwanted) two fonts ("Arial" and "New Times Roman") and two font sizes ("12" and "24"). Moreover the copied output  get randomly fat formatting.

Example:

![bug7](https://cloud.githubusercontent.com/assets/22355317/22333134/ac23c7fe-e3d4-11e6-8a1e-269839edcf1e.jpg)

<i>Used Software: Word 2010, OpenOffice 4, LibreOffice 5.1</i>
<i>CogStat Version: Latest update from 13.12.16</i>
<i>System: Windows 10</i>

**Comment by krajcsi** [comment]
With more appropriate style handling of the output, this issue is basically solved.
